/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WingoGameResult {
    winningNumber: bigint;
    colorResult: Variant_red_green_violet;
}
export type WingoBetType = {
    __kind__: "color";
    color: {
        color: Variant_red_green;
    };
} | {
    __kind__: "numberValue";
    numberValue: {
        value: bigint;
    };
} | {
    __kind__: "violet";
    violet: null;
};
export interface WingoBet {
    player: Principal;
    roundResult?: WingoGameResult;
    betType: WingoBetType;
    roundId: bigint;
    amount: bigint;
}
export interface UserProfile {
    name: string;
}
export interface WingoRound {
    id: bigint;
    startTime: bigint;
    winningNumber?: bigint;
    endTime: bigint;
    colorResult?: Variant_red_green_violet;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_red_green {
    red = "red",
    green = "green"
}
export enum Variant_red_green_violet {
    red = "red",
    green = "green",
    violet = "violet"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getBetHistory(limit: bigint): Promise<Array<WingoBet>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentRound(): Promise<WingoRound>;
    getRoundHistory(limit: bigint): Promise<Array<WingoRound>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeBet(roundId: bigint, betType: WingoBetType, amount: bigint): Promise<void>;
    resolveRound(roundId: bigint, winningNumber: bigint, colorResult: Variant_red_green_violet): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole, WingoBet as _WingoBet, WingoBetType as _WingoBetType, WingoGameResult as _WingoGameResult, WingoRound as _WingoRound } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getBetHistory(arg0: bigint): Promise<Array<WingoBet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBetHistory(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBetHistory(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentRound(): Promise<WingoRound> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRound();
                return from_candid_WingoRound_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRound();
            return from_candid_WingoRound_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoundHistory(arg0: bigint): Promise<Array<WingoRound>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoundHistory(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoundHistory(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBet(arg0: bigint, arg1: WingoBetType, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0, to_candid_WingoBetType_n22(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0, to_candid_WingoBetType_n22(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async resolveRound(arg0: bigint, arg1: bigint, arg2: Variant_red_green_violet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveRound(arg0, arg1, to_candid_variant_n26(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveRound(arg0, arg1, to_candid_variant_n26(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_WingoBetType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WingoBetType): WingoBetType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_WingoBet_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WingoBet): WingoBet {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_WingoGameResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WingoGameResult): WingoGameResult {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_WingoRound_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WingoRound): WingoRound {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        red: null;
    } | {
        green: null;
    } | {
        violet: null;
    }]): Variant_red_green_violet | null {
    return value.length === 0 ? null : from_candid_variant_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WingoGameResult]): WingoGameResult | null {
    return value.length === 0 ? null : from_candid_WingoGameResult_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: {
        red: null;
    } | {
        green: null;
    };
}): {
    color: Variant_red_green;
} {
    return {
        color: from_candid_variant_n13(_uploadFile, _downloadFile, value.color)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    winningNumber: [] | [bigint];
    endTime: bigint;
    colorResult: [] | [{
            red: null;
        } | {
            green: null;
        } | {
            violet: null;
        }];
}): {
    id: bigint;
    startTime: bigint;
    winningNumber?: bigint;
    endTime: bigint;
    colorResult?: Variant_red_green_violet;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        winningNumber: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.winningNumber)),
        endTime: value.endTime,
        colorResult: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.colorResult))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    player: Principal;
    roundResult: [] | [_WingoGameResult];
    betType: _WingoBetType;
    roundId: bigint;
    amount: bigint;
}): {
    player: Principal;
    roundResult?: WingoGameResult;
    betType: WingoBetType;
    roundId: bigint;
    amount: bigint;
} {
    return {
        player: value.player,
        roundResult: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.roundResult)),
        betType: from_candid_WingoBetType_n10(_uploadFile, _downloadFile, value.betType),
        roundId: value.roundId,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    winningNumber: bigint;
    colorResult: {
        red: null;
    } | {
        green: null;
    } | {
        violet: null;
    };
}): {
    winningNumber: bigint;
    colorResult: Variant_red_green_violet;
} {
    return {
        winningNumber: value.winningNumber,
        colorResult: from_candid_variant_n9(_uploadFile, _downloadFile, value.colorResult)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: {
        color: {
            red: null;
        } | {
            green: null;
        };
    };
} | {
    numberValue: {
        value: bigint;
    };
} | {
    violet: null;
}): {
    __kind__: "color";
    color: {
        color: Variant_red_green;
    };
} | {
    __kind__: "numberValue";
    numberValue: {
        value: bigint;
    };
} | {
    __kind__: "violet";
    violet: null;
} {
    return "color" in value ? {
        __kind__: "color",
        color: from_candid_record_n12(_uploadFile, _downloadFile, value.color)
    } : "numberValue" in value ? {
        __kind__: "numberValue",
        numberValue: value.numberValue
    } : "violet" in value ? {
        __kind__: "violet",
        violet: value.violet
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
}): Variant_red_green {
    return "red" in value ? Variant_red_green.red : "green" in value ? Variant_red_green.green : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    violet: null;
}): Variant_red_green_violet {
    return "red" in value ? Variant_red_green_violet.red : "green" in value ? Variant_red_green_violet.green : "violet" in value ? Variant_red_green_violet.violet : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WingoRound>): Array<WingoRound> {
    return value.map((x)=>from_candid_WingoRound_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WingoBet>): Array<WingoBet> {
    return value.map((x)=>from_candid_WingoBet_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WingoBetType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WingoBetType): _WingoBetType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: Variant_red_green;
}): {
    color: {
        red: null;
    } | {
        green: null;
    };
} {
    return {
        color: to_candid_variant_n25(_uploadFile, _downloadFile, value.color)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "color";
    color: {
        color: Variant_red_green;
    };
} | {
    __kind__: "numberValue";
    numberValue: {
        value: bigint;
    };
} | {
    __kind__: "violet";
    violet: null;
}): {
    color: {
        color: {
            red: null;
        } | {
            green: null;
        };
    };
} | {
    numberValue: {
        value: bigint;
    };
} | {
    violet: null;
} {
    return value.__kind__ === "color" ? {
        color: to_candid_record_n24(_uploadFile, _downloadFile, value.color)
    } : value.__kind__ === "numberValue" ? {
        numberValue: value.numberValue
    } : value.__kind__ === "violet" ? {
        violet: value.violet
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_red_green): {
    red: null;
} | {
    green: null;
} {
    return value == Variant_red_green.red ? {
        red: null
    } : value == Variant_red_green.green ? {
        green: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_red_green_violet): {
    red: null;
} | {
    green: null;
} | {
    violet: null;
} {
    return value == Variant_red_green_violet.red ? {
        red: null
    } : value == Variant_red_green_violet.green ? {
        green: null
    } : value == Variant_red_green_violet.violet ? {
        violet: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
