/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WingoBet {
  'player' : Principal,
  'roundResult' : [] | [WingoGameResult],
  'betType' : WingoBetType,
  'roundId' : bigint,
  'amount' : bigint,
}
export type WingoBetType = {
    'color' : { 'color' : { 'red' : null } | { 'green' : null } }
  } |
  { 'numberValue' : { 'value' : bigint } } |
  { 'violet' : null };
export interface WingoGameResult {
  'winningNumber' : bigint,
  'colorResult' : { 'red' : null } |
    { 'green' : null } |
    { 'violet' : null },
}
export interface WingoRound {
  'id' : bigint,
  'startTime' : bigint,
  'winningNumber' : [] | [bigint],
  'endTime' : bigint,
  'colorResult' : [] | [
    { 'red' : null } |
      { 'green' : null } |
      { 'violet' : null }
  ],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBetHistory' : ActorMethod<[bigint], Array<WingoBet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRound' : ActorMethod<[], WingoRound>,
  'getRoundHistory' : ActorMethod<[bigint], Array<WingoRound>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[bigint, WingoBetType, bigint], undefined>,
  'resolveRound' : ActorMethod<
    [
      bigint,
      bigint,
      { 'red' : null } |
        { 'green' : null } |
        { 'violet' : null },
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];