/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WingoGameResult = IDL.Record({
  'winningNumber' : IDL.Nat,
  'colorResult' : IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'violet' : IDL.Null,
  }),
});
export const WingoBetType = IDL.Variant({
  'color' : IDL.Record({
    'color' : IDL.Variant({ 'red' : IDL.Null, 'green' : IDL.Null }),
  }),
  'numberValue' : IDL.Record({ 'value' : IDL.Nat }),
  'violet' : IDL.Null,
});
export const WingoBet = IDL.Record({
  'player' : IDL.Principal,
  'roundResult' : IDL.Opt(WingoGameResult),
  'betType' : WingoBetType,
  'roundId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WingoRound = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'winningNumber' : IDL.Opt(IDL.Nat),
  'endTime' : IDL.Int,
  'colorResult' : IDL.Opt(
    IDL.Variant({ 'red' : IDL.Null, 'green' : IDL.Null, 'violet' : IDL.Null })
  ),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBetHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WingoBet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRound' : IDL.Func([], [WingoRound], ['query']),
  'getRoundHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WingoRound)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([IDL.Nat, WingoBetType, IDL.Nat], [], []),
  'resolveRound' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'red' : IDL.Null,
          'green' : IDL.Null,
          'violet' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WingoGameResult = IDL.Record({
    'winningNumber' : IDL.Nat,
    'colorResult' : IDL.Variant({
      'red' : IDL.Null,
      'green' : IDL.Null,
      'violet' : IDL.Null,
    }),
  });
  const WingoBetType = IDL.Variant({
    'color' : IDL.Record({
      'color' : IDL.Variant({ 'red' : IDL.Null, 'green' : IDL.Null }),
    }),
    'numberValue' : IDL.Record({ 'value' : IDL.Nat }),
    'violet' : IDL.Null,
  });
  const WingoBet = IDL.Record({
    'player' : IDL.Principal,
    'roundResult' : IDL.Opt(WingoGameResult),
    'betType' : WingoBetType,
    'roundId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WingoRound = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'winningNumber' : IDL.Opt(IDL.Nat),
    'endTime' : IDL.Int,
    'colorResult' : IDL.Opt(
      IDL.Variant({ 'red' : IDL.Null, 'green' : IDL.Null, 'violet' : IDL.Null })
    ),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBetHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WingoBet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRound' : IDL.Func([], [WingoRound], ['query']),
    'getRoundHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WingoRound)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([IDL.Nat, WingoBetType, IDL.Nat], [], []),
    'resolveRound' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'red' : IDL.Null,
            'green' : IDL.Null,
            'violet' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };